variables:
  WORK: "/tmp"
  LMOD_REDIRECT: "yes"
  MODULES_DIR: "/util/opt/modulefiles"
  LMOD_HOME: "/util/opt/lmod/lmod"
  TF_LIST: "/util/opt/modulefiles/tensorflow_module_list.txt"

stages:
  - test
  - deploy

test-modules:
  stage: test
  image: unlhcc/crane-build-el8
  except:
    - master
  tags:
    - docker
  before_script:
    - ln -s $CI_PROJECT_DIR $MODULES_DIR
    - source $LMOD_HOME/init/profile
  script:
    - module av > /dev/null
    - module spider > /dev/null

test-paths:
  stage: test
  image: unlhcc/crane-build-el8
  except:
    - master
  tags:
    - crane-el8
  script:
    - scripts/test_changed_modules.sh

deploy:
  stage: deploy
  environment:
    name: crane_production
    url: https://crane.unl.edu
  resource_group: production
  image: unlhcc/crane-build-el8
  only:
    - master
  tags:
    - crane-el8
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
    - source $LMOD_HOME/init/profile
    - module load lmod
  script:
    - cd $MODULES_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA
    - cp -fv SitePackage.lua $LMOD_HOME/libexec
    - update_lmod_system_cache_files -d $MODULES_DIR/cacheDir -t $MODULES_DIR/cacheTS.txt $MODULES_DIR
    - module use /util/opt/hcc-modules/Common && module -t avail tensorflow |& grep tensorflow 2>/dev/null > $TF_LIST
